FROM python:3.7-stretch

# Requirements for sdl
RUN apt-get update && apt-get install -y \
    gcc \
    musl-dev \
    curl \
    apt-utils \
    && rm -rf /var/lib/apt/lists/*

# RMR repository
RUN curl -s "https://packagecloud.io/install/repositories/o-ran-sc/release/script.deb.sh" | bash

# Install RMR library
RUN mkdir -p /opt/route/
COPY ./auto_mato/route.rt /opt/route/route.rt
ENV LD_LIBRARY_PATH /usr/local/lib/:/usr/local/lib64
ENV RMR_SEED_RT /opt/route/route.rt

RUN apt-get update && apt-get install -y \
    rmr=4.7.4 \
    && rm -rf /var/lib/apt/lists/*

# Install poetry
RUN python3 -m pip install --upgrade pip
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
ENV PATH = "${PATH}:/root/.poetry/bin"

# Copy python package
COPY pyproject.toml .

# Install package
RUN poetry install --no-dev


COPY ./auto_mato ./auto_mato
COPY ./data/basic_prediction_model.pkl ./data/basic_prediction_model.pkl
RUN poetry install --no-dev

# Run
ENV PYTHONUNBUFFERED 1
CMD poetry run python3 ./auto_mato/decision_xapp.py
