# ==================================================================================
#       Copyright (c) 2019-2020 Nokia
#       Copyright (c) 2018-2020 AT&T Intellectual Property.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ==================================================================================
FROM python:3.8-alpine

# copy rmr libraries from builder image in lieu of an Alpine package
COPY --from=nexus3.o-ran-sc.org:10002/o-ran-sc/bldr-alpine3-rmr:4.5.2 /usr/local/lib64/librmr* /usr/local/lib64/
# RMR setup
RUN mkdir -p /opt/route/
COPY ./auto_mato/route.rt /opt/route/route.rt
ENV LD_LIBRARY_PATH /usr/local/lib/:/usr/local/lib64
ENV RMR_SEED_RT /opt/route/route.rt

# sdl needs gcc
RUN apk update && apk add gcc musl-dev bash

# Install curl
RUN apk add --update curl && \
    rm -rf /var/cache/apk/*

# Install poetry
RUN python3 -m pip install --upgrade pip
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
ENV PATH = "${PATH}:/root/.poetry/bin"

# Copy python package
COPY pyproject.toml .

# Install package
RUN poetry install --no-dev

COPY ./auto_mato ./auto_mato
RUN poetry install --no-dev

# Run
ENV PYTHONUNBUFFERED 1
CMD poetry run python3 ./auto_mato/decision_xapp.py
